hotsauce/config/routes.rb
Rails.application.routes.draw do
  resources :sauces

  devise_for :users, controllers: {registrations: 'registrations'}
  root "sauces#index"
  get "about" => "pages#about"

end

hotsauce/app/models/sauce.rb
class Sauce < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	scope :vegan_user, lambda { |user|
    	where(:vegan => user.vegan) unless user.vegan == false
  	}

  	scope :gluten_user, lambda { |user|
    	where(:no_gluten => user.no_gluten) unless user.no_gluten == false
  	}

  	scope :alcohol_user, lambda { |user|
    	where(:no_alcohol => user.no_alcohol) unless user.no_alcohol == false
  	}
end

hotsauce/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :current_password
  has_many :sauces       
end

hotsauce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :name, :mild, :medium, :hot, :hotter, :hottest, :superhot, :sweet, :smoke, :fruit, :vinegar, :garlic, :salt, :vegan, :no_gluten, :no_alcohol)}
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password,:current_password, :password_confirmation, :name, :mild, :medium, :hot, :hotter, :hottest, :superhot, :sweet, :smoke, :fruit, :vinegar, :garlic, :salt, :vegan, :no_gluten, :no_alcohol)}
end
end

	

hotsauce/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

hotsauce/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def update_resource(resource, params)
      if params[:password].blank? && params[:password_confirmation].blank?
      resource.update_without_password(params)
    else
     super
    end
  end
end

hotsauce/app/controllers/sauces_controller.rb
class SaucesController < ApplicationController
  before_action :set_sauce, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /sauces
  # GET /sauces.json
  def index
     if current_user.nil?
      @sauces = Sauce.all
     else 
      @sauces = Sauce.all.joins(:user)
      .vegan_user(current_user)
      .gluten_user(current_user)
      .alcohol_user(current_user)
      .order("((users.sweet - sauces.sweet)*(users.sweet - sauces.sweet))+((users.smoke - sauces.smoke)*(users.smoke - sauces.smoke))+((users.fruit - sauces.fruit)*(users.fruit - sauces.fruit))+((users.garlic - sauces.garlic)*(users.garlic - sauces.garlic))+((users.vinegar - sauces.vinegar)*(users.vinegar - sauces.vinegar))+((users.salt - sauces.salt)*(users.salt - sauces.salt))")
      #.where("(users.vegan = sauces.vegan) and (users.no_alcohol = sauces.no_alcohol) and (users.no_gluten = sauces.no_gluten) and( (users.mild = sauces.mild) or (users.medium = sauces.medium) or (users.hot = sauces.hot) or (users.hotter = sauces.hotter) or (users.hottest = sauces.hottest) or (users.superhot = sauces.superhot) )")
    end
  end

  # GET /sauces/1
  # GET /sauces/1.json
  def show

  end

  # GET /sauces/new
  def new
    @sauce = current_user.sauces.build
  end

  # GET /sauces/1/edit
  def edit
  end

  # POST /sauces
  # POST /sauces.json
  def create
    @sauce = current_user.sauces.build(sauce_params)

    respond_to do |format|
      if @sauce.save
        format.html { redirect_to @sauce, notice: 'Sauce was successfully created.' }
        format.json { render :show, status: :created, location: @sauce }
      else
        format.html { render :new }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sauces/1
  # PATCH/PUT /sauces/1.json
  def update
    respond_to do |format|
      if @sauce.update(sauce_params)
        format.html { redirect_to @sauce, notice: 'Sauce was successfully updated.' }
        format.json { render :show, status: :ok, location: @sauce }
      else
        format.html { render :edit }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sauces/1
  # DELETE /sauces/1.json
  def destroy
    @sauce.destroy
    respond_to do |format|
      format.html { redirect_to sauces_url, notice: 'Sauce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sauce
      @sauce = Sauce.find(params[:id])
    end

    def correct_user
      @sauce = current_user.sauces.find_by(id: params[:id])
      redirect_to sauces_path, notice: "Not authorized to edit this sauce" if @sauce.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sauce_params
      params.require(:sauce).permit(:image, :description,:mild, :medium, :hot, :hotter, :hottest, :superhot, :sweet, :smoke, :fruit, :vinegar, :garlic, :salt, :vegan, :no_gluten, :no_alcohol)
    end
end

hotsauce/app/helpers/application_helper.rb
module ApplicationHelper
end

hotsauce/app/helpers/pages_helper.rb
module PagesHelper
end

hotsauce/app/helpers/sauces_helper.rb
module SaucesHelper
end

hotsauce/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= "http://heatonist.com" rel="external" >Heatonist</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <!--      Commenting out dropdown

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
    -->
<!--      Commenting out search bar

        <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </div><!-- /.container -->
</nav>

hotsauce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heatonist Find My Sauce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<!--<%= link_to "home", root_path %>.</p>
	<%= link_to "about", about_path %>.</p> -->
	<div class="container">
		<% flash.each do |name, msg| %>
     		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

hotsauce/app/views/pages/_home.html.erb
<div class="jumbotron center">
     <h1>Find your new favorite hot sauce!</h1>
     <% if user_signed_in? %>
     	#do something
     <% else %>
     <p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  	</p>
  	<%end%>
</div>

hotsauce/app/views/pages/about.html.erb
<h1> About us </h1>
<p> We are working on stuff <p>

hotsauce/app/views/sauces/_form.html.erb
<%= form_for @sauce, html: { multipart: true } do |f| %>
  <% if @sauce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sauce.errors.count, "error") %> prohibited this sauce from being saved:</h2>

      <ul>
      <% @sauce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
  <h2>Select your heat level</h2>
    <%= f.label :mild %>
    <%= f.check_box :mild, autofocus: true, class: "form-control" %>

    <%= f.label :medium %>
    <%= f.check_box :medium, autofocus: true, class: "form-control" %>

    <%= f.label :hot %>
    <%= f.check_box :hot, autofocus: true, class: "form-control" %>

    <%= f.label :hotter %>
    <%= f.check_box :hotter, autofocus: true, class: "form-control" %>

    <%= f.label :hottest %>
    <%= f.check_box :hottest, autofocus: true, class: "form-control" %>

    <%= f.label :superhot %>
    <%= f.check_box :superhot, autofocus: true, class: "form-control" %>
 </div>

 <div class="form-group">
  <h2>Sweet sauce? (rating from 1 to 5) </h2>
    <%= f.label :sweet %>
    <%= f.number_field :sweet, autofocus: true, class: "form-control" %></div>

 <div class="form-group">
  <h2>Smoky sauce? (rating from 1 to 5) </h2>
    <%= f.label :smoke %>
    <%= f.number_field :smoke, autofocus: true, class: "form-control" %></div>

 <div class="form-group">
  <h2>Fruity sauce? (rating from 1 to 5) </h2>
    <%= f.label :fruit %>
    <%= f.number_field :fruit, autofocus: true, class: "form-control" %></div>

 <div class="form-group">
  <h2>Vinegar? (rating from 1 to 5) </h2>
    <%= f.label :vinegar %>
    <%= f.number_field :vinegar, autofocus: true, class: "form-control" %></div>

 <div class="form-group">
  <h2>Garlic? (rating from 1 to 5) </h2>
    <%= f.label :garlic %>
    <%= f.number_field :garlic, autofocus: true, class: "form-control" %></div>

 <div class="form-group">
  <h2>Salty sauce? (rating from 1 to 5) </h2>
    <%= f.label :salt %>
    <%= f.number_field :salt, autofocus: true, class: "form-control" %></div>
 
 <div class="field">
  <h2>Select any dietary restrictions</h2>
    <%= f.label :vegan %>
    <%= f.check_box :vegan, autofocus: true, class: "form-control" %>

    <%= f.label :no_gluten %>
    <%= f.check_box :no_gluten, autofocus: true, class: "form-control" %>

    <%= f.label :no_alcohol %>
    <%= f.check_box :no_alcohol, autofocus: true, class: "form-control" %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hotsauce/app/views/sauces/edit.html.erb
<h1>Editing sauce</h1>

<%= render 'form' %>

<%= link_to 'Show', @sauce %> |
<%= link_to 'Back', sauces_path %>

hotsauce/app/views/sauces/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<% if user_signed_in? %>
  <%= link_to 'New Sauce', new_sauce_path %>
<% end %>


<div id="sauces" class="transitions-enabled">
  <% @sauces.each do |sauce| %>
    <div class="box panel panel-default">
      <%= image_tag sauce.image.url %>
      <div class="panel-body">
        <%= sauce.description %>
        <%= link_to 'Show', sauce %>
        <% if sauce.user == current_user %>
          <%= link_to 'Edit', edit_sauce_path(sauce) %>
          <%= link_to 'Destroy', sauce, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    </div>
  <% end %>
</div>

hotsauce/app/views/sauces/new.html.erb
<h1>New sauce</h1>

<%= render 'form' %>

<%= link_to 'Back', sauces_path %>

hotsauce/app/views/sauces/show.html.erb
<%= image_tag @sauce.image.url %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @sauce.description %>
</p>

<% if @sauce.user == current_user %>
	<%= link_to 'Edit', edit_sauce_path(@sauce) %> |
<% end %>
<%= link_to 'Back', sauces_path %>